### PR TITLE
Better error from a bad application ID response

### LINKED ISSUE #173: [BUG] IQ App ID error logging and settings change
Reported by @maurycupitt and reproduced by me, error message when the App ID does not exist in IQ is not clear:
image

Changing the App ID to something that exists within the settings and re-evaluating does not work and requires a restart of vscode to take effect:
image

After restart:
image

cc @bhamail / @DarthHater

### PR DESCRIPTION
**Pull request by DarthHater**
Based on #173 , I wanted to see if it was easy to improve the error logged, as well as just handle everything better.

This pull request makes the following changes:
* Strongly types the app response, so we can do some better stuff with time (what if you find two apps, which one is it?!?!, etc....)
* Moves the logic to parse out the application ID inside the service (it's more appropriate here, consumer shouldn't really care how to parse the json in this case)
* ????
* PROFIT!!!!

It relates to the following issue #s:
* Fixes #173 #87 

cc @bhamail / @DarthHater

### CODE REVIEW

File: ext-src/models/IqComponentModel.ts [hunk 1]
```diff
@@ -96,12 +96,10 @@ export class IqComponentModel implements ComponentModel {
...
               progress.report({message: "Getting IQ Server Internal Application ID", increment: 40});
               
-              let response: string = await this.requestService.getApplicationId(this.applicationPublicId);
-              this.logger.log(LogLevel.TRACE, `Obtained internal application ID response`, response);
-              
-              let appRep = JSON.parse(response);
+              let internalID: string = await this.requestService.getApplicationId(this.applicationPublicId);
+              this.logger.log(LogLevel.TRACE, `Obtained internal application ID response`, internalID);
         
-              this.requestService.setApplicationId(appRep.applications[0].id);
```
Comment (DarthHater) [inline ext-src/models/IqComponentModel.ts:104]: This was causing the bad error message @ButterB0wl , etc... (because it was trying to access a property on an empty object, more or less. Moved this into the service, can test for it now, etc...

File: ext-src/services/IqRequestService.ts [hunk 2]
```diff
@@ -82,9 +83,25 @@ export class IqRequestService implements RequestService {
...
+              return;
+            } else {
+              this.logger.log(
+                LogLevel.ERROR,
+                `No valid application found using the public ID: ${applicationPublicId}`, 
+                url,
+                json,
+                appRep
+              );
+              reject(`No valid application found using the public ID: ${applicationPublicId}`);
```
Comment (DarthHater) [inline ext-src/services/IqRequestService.ts:100]: This probably double logs, but I was kinda like, meh, I think that's ok?

**Review by ButterB0wl — COMMENTED** [review]
Failing out on this branch:
image
```

"startTime":"2021-01-19T21:30:12.957Z","categoryName":"sonatypeIQ","data":["Starting to Munch on I dependencies"],"level":{"level":20000,"levelStr":"INFO","colour":"green"},"context":{},"pid":6989},
{"startTime":"2021-01-19T21:30:13.082Z","categoryName":"sonatypeIQ","data":["Obtained Dependencies from Muncher",[{"Name":"github.com/BurntSushi/toml","Version":"v0.3.1"},{"Name":"github.com/Flaque/filet","Version":"v0.0.0-20190209224823-fc4d33cfcf93"},{"Name":"github.com/Masterminds/semver","Version":"v0.0.0-20180403130225-3c92f33da7a8"},{"Name":"github.com/Masterminds/vcs","Version":"v1.13.1"},{"Name":"github.com/armon/go-radix","Version":"v1.0.0"},{"Name":"github.com/asaskevich/govalidator","Version":"v0.0.0-20180720115003-f9ffefc3facf"},{"Name":"github.com/beevik/etree","Version":"v1.1.0"},{"Name":"github.com/boltdb/bolt","Version":"v1.3.1"},{"Name":"github.com/common-nighthawk/go-figure","Version":"v0.0.0-20190529165535-67e0ed34491a"},{"Name":"github.com/davecgh/go-spew","Version":"v1.1.1"},{"Name":"github.com/globalsign/mgo","Version":"v0.0.0-20181015135952-eeefdecb41b8"},{"Name":"github.com/go-openapi/errors","Version":"v0.19.0"},{"Name":"github.com/go-openapi/strfmt","Version":"v0.19.0"},{"Name":"github.com/golang/dep","Version":"v0.5.4"},{"Name":"github.com/golang/protobuf","Version":"v1.2.0"},{"Name":"github.com/google/go-cmp","Version":"v0.4.0"},{"Name":"github.com/google/uuid","Version":"v1.1.1"},{"Name":"github.com/gorilla/websocket","Version":"v1.4.0"},{"Name":"github.com/jarcoal/httpmock","Version":"v1.0.4"},{"Name":"github.com/jedib0t/go-pretty/v6","Version":"v6.0.2"},{"Name":"github.com/jmank88/nuts","Version":"v0.3.0"},{"Name":"github.com/konsorten/go-windows-terminal-sequences","Version":"v1.0.2"},{"Name":"github.com/kr/pretty","Version":"v0.1.0"},{"Name":"github.com/kr/pty","Version":"v1.1.1"},{"Name":"github.com/kr/text","Version":"v0.1.0"},{"Name":"github.com/logrusorgru/aurora","Version":"v0.0.0-20190803045625-94edacc10f9b"},{"Name":"github.com/mailru/easyjson","Version":"v0.0.0-20190403194419-1ea4449da983"},{"Name":"github.com/mattn/go-runewidth","Version":"v0.0.9"},{"Name":"github.com/mitchellh/mapstructure","Version":"v1.1.2"},{"Name":"github.com/nightlyone/lockfile","Version":"v0.0.0-20180618180623-0ad87eef1443"},{"Name":"github.com/package-url/packageurl-go","Version":"v0.1.0"},{"Name":"github.com/pelletier/go-toml","Version":"v1.4.0"},{"Name":"github.com/pkg/errors","Version":"v0.8.0"},{"Name":"github.com/pkg/profile","Version":"v1.2.1"},{"Name":"github.com/pmezard/go-difflib","Version":"v1.0.0"},{"Name":"github.com/recoilme/pudge","Version":"v1.0.3"},{"Name":"github.com/sdboyer/constext","Version":"v0.0.0-20170321163424-836a14457353"},{"Name":"github.com/shopspring/decimal","Version":"v0.0.0-20180709203117-cd690d0c9e24"},{"Name":"github.com/sirupsen/logrus","Version":"v1.5.0"},{"Name":"github.com/sonatype-nexus-community/nancy","Version":"v0.3.1"},{"Name":"github.com/spf13/afero","Version":"v1.2.2"},{"Name":"github.com/stretchr/objx","Version":"v0.1.0"},{"Name":"github.com/stretchr/testify","Version":"v1.3.0"},{"Name":"golang.org/x/crypto","Version":"v0.0.0-20200311171314-f7b00557c8c4"},{"Name":"golang.org/x/net","Version":"v0.0.0-20190404232315-eb5bcb51f2a3"},{"Name":"golang.org/x/sync","Version":"v0.0.0-20200317015054-43a5402ce75a"},{"Name":"golang.org/x/sys","Version":"v0.0.0-20200519105757-fe76b779f299"},{"Name":"golang.org/x/text","Version":"v0.3.0"},{"Name":"golang.org/x/xerrors","Version":"v0.0.0-20191204190536-9bdfabe68543"},{"Name":"gopkg.in/check.v1","Version":"v1.0.0-20180628173108-788fd7840127"},{"Name":"gopkg.in/go-playground/assert.v1","Version":"v1.2.1"},{"Name":"gopkg.in/yaml.v2","Version":"v2.2.8"}]],"level":{"level":5000,"levelStr":"TRACE","colour":"blue"},"context":{},"pid":6989},
{"startTime":"2021-01-19T21:30:13.083Z","categoryName":"sonatypeIQ","data":["Starting to Munch on k dependencies"],"level":{"level":20000,"levelStr":"INFO","colour":"green"},"context":{},"pid":6989},
{"startTime":"2021-01-19T21:30:13.086Z","categoryName":"sonatypeIQ","data":["Obtained Dependencies from Muncher",[{"Name":"anytree","Version":"2.8.0","Extension":"tar.gz","Qualifier":""},{"Name":"astroid","Version":"2.4.0","Extension":"tar.gz","Qualifier":""},{"Name":"cachetools","Version":"4.1.0","Extension":"tar.gz","Qualifier":""},{"Name":"certifi","Version":"2020.4.5.1","Extension":"tar.gz","Qualifier":""},{"Name":"chardet","Version":"3.0.4","Extension":"tar.gz","Qualifier":""},{"Name":"click","Version":"7.1.2","Extension":"tar.gz","Qualifier":""},{"Name":"colorama","Version":"0.4.3","Extension":"tar.gz","Qualifier":""},{"Name":"distlib","Version":"0.3.0","Extension":"tar.gz","Qualifier":""},{"Name":"docutils","Version":"0.16","Extension":"tar.gz","Qualifier":""},{"Name":"idna","Version":"2.7","Extension":"tar.gz","Qualifier":""},{"Name":"isort","Version":"4.3.21","Extension":"tar.gz","Qualifier":""},{"Name":"jake","Version":"0.2.24","Extension":"tar.gz","Qualifier":""},{"Name":"johnnydep","Version":"1.5","Extension":"tar.gz","Qualifier":""},{"Name":"lazy-object-proxy","Version":"1.4.3","Extension":"tar.gz","Qualifier":""},{"Name":"lxml","Version":"4.5.0","Extension":"tar.gz","Qualifier":""},{"Name":"mccabe","Version":"0.6.1","Extension":"tar.gz","Qualifier":""},{"Name":"oyaml","Version":"0.9","Extension":"tar.gz","Qualifier":""},{"Name":"packaging","Version":"20.3","Extension":"tar.gz","Qualifier":""},{"Name":"pkginfo","Version":"1.5.0.1","Extension":"tar.gz","Qualifier":""},{"Name":"polling","Version":"0.3.1","Extension":"tar.gz","Qualifier":""},{"Name":"pyfiglet","Version":"0.8.post1","Extension":"tar.gz","Qualifier":""},{"Name":"pylint","Version":"2.5.0","Extension":"tar.gz","Qualifier":""},{"Name":"pyparsing","Version":"2.4.7","Extension":"tar.gz","Qualifier":""},{"Name":"python-dateutil","Version":"2.8.1","Extension":"tar.gz","Qualifier":""},{"Name":"PyYAML","Version":"5.3.1","Extension":"tar.gz","Qualifier":""},{"Name":"requests","Version":"2.19.1","Extension":"tar.gz","Qualifier":""},{"Name":"six","Version":"1.14.0","Extension":"tar.gz","Qualifier":""},{"Name":"structlog","Version":"20.1.0","Extension":"tar.gz","Qualifier":""},{"Name":"tabulate","Version":"0.8.7","Extension":"tar.gz","Qualifier":""},{"Name":"termcolor","Version":"1.1.0","Extension":"tar.gz","Qualifier":""},{"Name":"terminaltables","Version":"3.1.0","Extension":"tar.gz","Qualifier":""},{"Name":"tinydb","Version":"3.15.2","Extension":"tar.gz","Qualifier":""},{"Name":"toml","Version":"0.10.0","Extension":"tar.gz","Qualifier":""},{"Name":"typed-ast","Version":"1.4.1","Extension":"tar.gz","Qualifier":""},{"Name":"urllib3","Version":"1.23","Extension":"tar.gz","Qualifier":""},{"Name":"wimpy","Version":"0.6","Extension":"tar.gz","Qualifier":""},{"Name":"wrapt","Version":"1.12.1","Extension":"tar.gz","Qualifier":""},{"Name":"yaspin","Version":"0.16.0","Extension":"tar.gz","Qualifier":""}]],"level":{"level":5000,"levelStr":"TRACE","colour":"blue"},"context":{},"pid":6989},
{"startTime":"2021-01-19T21:30:13.087Z","categoryName":"sonatypeIQ","data":["Starting to Munch on j dependencies"],"level":{"level":20000,"levelStr":"INFO","colour":"green"},"context":{},"pid":6989},
{"startTime":"2021-01-19T21:30:13.092Z","categoryName":"sonatypeIQ","data":["Obtained Dependencies from Muncher",[{"Name":"Ascii85","Version":"1.0.3"},{"Name":"actioncable","Version":"6.0.3.4"},{"Name":"actionmailbox","Version":"6.0.3.4"},{"Name":"actionmailer","Version":"6.0.3.4"},{"Name":"actionpack","Version":"6.0.3.4"},{"Name":"actiontext","Version":"6.0.3.4"},{"Name":"actionview","Version":"6.0.3.4"},{"Name":"activejob","Version":"6.0.3.4"},{"Name":"activemodel","Version":"6.0.3.4"},{"Name":"activerecord","Version":"6.0.3.4"},{"Name":"activestorage","Version":"6.0.3.4"},{"Name":"activesupport","Version":"6.0.3.4"},{"Name":"addressable","Version":"2.7.0"},{"Name":"afm","Version":"0.2.2"},{"Name":"ast","Version":"2.4.1"},{"Name":"autoprefixer-rails","Version":"10.0.1.0"},{"Name":"bcrypt","Version":"3.1.15"},{"Name":"bootsnap","Version":"1.4.7"},{"Name":"bootstrap","Version":"4.5.2"},{"Name":"bootstrap_form","Version":"4.5.0"},{"Name":"bson","Version":"4.10.0"},{"Name":"bson_ext","Version":"1.5.1"},{"Name":"builder","Version":"3.2.4"},{"Name":"bundler-audit","Version":"0.7.0.1"},{"Name":"byebug","Version":"11.1.3"},{"Name":"capybara","Version":"2.18.0"},{"Name":"capybara-screenshot","Version":"1.0.24"},{"Name":"childprocess","Version":"3.0.0"},{"Name":"codecov","Version":"0.2.5"},{"Name":"coderay","Version":"1.1.3"},{"Name":"coffee-rails","Version":"5.0.0"},{"Name":"coffee-script","Version":"2.4.1"},{"Name":"coffee-script-source","Version":"1.12.2"},{"Name":"colorize","Version":"0.8.1"},{"Name":"concurrent-ruby","Version":"1.1.7"},{"Name":"crass","Version":"1.0.6"},{"Name":"database_cleaner","Version":"1.8.5"},{"Name":"devise","Version":"4.7.2"},{"Name":"docile","Version":"1.3.2"},{"Name":"easy_diff","Version":"1.0.0"},{"Name":"enumerize","Version":"2.3.1"},{"Name":"erubi","Version":"1.9.0"},{"Name":"execjs","Version":"2.7.0"},{"Name":"factory_bot","Version":"6.1.0"},{"Name":"factory_bot_rails","Version":"6.1.0"},{"Name":"faker","Version":"2.13.0"},{"Name":"faraday","Version":"1.0.1"},{"Name":"ffi","Version":"1.13.1"},{"Name":"figaro","Version":"1.2.0"},{"Name":"geokit","Version":"1.13.1"},{"Name":"globalid","Version":"0.4.2"},{"Name":"hashery","Version":"2.1.2"},{"Name":"hashie","Version":"4.1.0"},{"Name":"highline","Version":"2.0.3"},{"Name":"i18n","Version":"1.8.5"},{"Name":"i18n-tasks","Version":"0.9.31"},{"Name":"jquery-rails","Version":"4.3.5"},{"Name":"jquery-ui-rails","Version":"6.0.1"},{"Name":"js-routes","Version":"1.4.9"},{"Name":"json","Version":"2.3.1"},{"Name":"jwt","Version":"2.2.1"},{"Name":"kaminari","Version":"1.2.1"},{"Name":"kaminari-actionview","Version":"1.2.1"},{"Name":"kaminari-activerecord","Version":"1.2.1"},{"Name":"kaminari-core","Version":"1.2.1"},{"Name":"kaminari-mongoid","Version":"1.0.1"},{"Name":"knapsack","Version":"1.18.0"},{"Name":"launchy","Version":"2.5.0"},{"Name":"libsqreen","Version":"0.6.1.0.1"},{"Name":"listen","Version":"3.1.5"},{"Name":"loofah","Version":"2.7.0"},{"Name":"mail","Version":"2.7.1"},{"Name":"marcel","Version":"0.3.3"},{"Name":"method_source","Version":"1.0.0"},{"Name":"mimemagic","Version":"0.3.5"},{"Name":"mini_backtrace","Version":"0.1.3"},{"Name":"mini_mime","Version":"1.0.2"},{"Name":"mini_portile2","Version":"2.4.0"},{"Name":"minitest","Version":"5.14.2"},{"Name":"minitest-ci","Version":"3.4.0"},{"Name":"minitest-optional_retry","Version":"0.0.2"},{"Name":"minitest-spec-rails","Version":"6.0.2"},{"Name":"minitest-stub-const","Version":"0.6"},{"Name":"mongo","Version":"2.13.0"},{"Name":"mongo_session_store","Version":"3.2.1"},{"Name":"mongoid","Version":"7.0.8"},{"Name":"mongoid-compatibility","Version":"0.5.1"},{"Name":"mongoid-history","Version":"0.8.3"},{"Name":"mongoid_rails_migrations","Version":"1.2.1"},{"Name":"msgpack","Version":"1.3.3"},{"Name":"multi_json","Version":"1.15.0"},{"Name":"multi_xml","Version":"0.6.0"},{"Name":"multipart-post","Version":"2.1.1"},{"Name":"nio4r","Version":"2.5.4"},{"Name":"nokogiri","Version":"1.10.10"},{"Name":"oauth2","Version":"1.4.4"},{"Name":"omniauth","Version":"1.9.1"},{"Name":"omniauth-google-oauth2","Version":"0.8.0"},{"Name":"omniauth-oauth2","Version":"1.6.0"},{"Name":"orm_adapter","Version":"0.5.0"},{"Name":"parallel","Version":"1.19.2"},{"Name":"parser","Version":"2.7.1.4"},{"Name":"pdf-core","Version":"0.8.1"},{"Name":"pdf-inspector","Version":"1.3.0"},{"Name":"pdf-reader","Version":"2.4.0"},{"Name":"popper_js","Version":"1.16.0"},{"Name":"prawn","Version":"2.3.0"},{"Name":"pry","Version":"0.13.1"},{"Name":"public_suffix","Version":"4.0.5"},{"Name":"puma","Version":"4.3.5"},{"Name":"rack","Version":"2.2.3"},{"Name":"rack-attack","Version":"5.4.2"},{"Name":"rack-proxy","Version":"0.6.5"},{"Name":"rack-test","Version":"1.1.0"},{"Name":"rails","Version":"6.0.3.4"},{"Name":"rails-dom-testing","Version":"2.0.3"},{"Name":"rails-html-sanitizer","Version":"1.3.0"},{"Name":"rails-i18n","Version":"6.0.0"},{"Name":"railties","Version":"6.0.3.4"},{"Name":"rainbow","Version":"3.0.0"},{"Name":"rake","Version":"13.0.1"},{"Name":"rb-fsevent","Version":"0.10.4"},{"Name":"rb-inotify","Version":"0.10.1"},{"Name":"rdoc","Version":"6.2.1"},{"Name":"regexp_parser","Version":"1.7.1"},{"Name":"render_async","Version":"2.1.7"},{"Name":"responders","Version":"3.0.1"},{"Name":"rexml","Version":"3.2.4"},{"Name":"rubocop","Version":"0.89.0"},{"Name":"rubocop-ast","Version":"0.3.0"},{"Name":"ruby-progressbar","Version":"1.10.1"},{"Name":"ruby-rc4","Version":"0.1.5"},{"Name":"ruby_audit","Version":"1.3.0"},{"Name":"ruby_dep","Version":"1.5.0"},{"Name":"rubyzip","Version":"2.3.0"},{"Name":"sass-rails","Version":"6.0.0"},{"Name":"sassc","Version":"2.4.0"},{"Name":"sassc-rails","Version":"2.1.2"},{"Name":"sdoc","Version":"1.0.0"},{"Name":"selenium-webdriver","Version":"3.142.7"},{"Name":"semantic_range","Version":"2.3.0"},{"Name":"sentry-raven","Version":"3.0.0"},{"Name":"shog","Version":"0.2.1"},{"Name":"shoulda-context","Version":"2.0.0"},{"Name":"simplecov","Version":"0.18.5"},{"Name":"simplecov-html","Version":"0.12.2"},{"Name":"sprockets","Version":"4.0.2"},{"Name":"sprockets-rails","Version":"3.2.2"},{"Name":"sq_mini_racer","Version":"0.2.5.0.1.beta3"},{"Name":"sqreen","Version":"1.20.3"},{"Name":"sqreen-backport","Version":"0.1.0"},{"Name":"sqreen-kit","Version":"0.2.2"},{"Name":"state_geo_tools","Version":"1.0.0"},{"Name":"terminal-table","Version":"1.8.0"},{"Name":"thor","Version":"1.0.1"},{"Name":"thread_safe","Version":"0.3.6"},{"Name":"tilt","Version":"2.0.10"},{"Name":"timecop","Version":"0.9.1"},{"Name":"ttfunk","Version":"1.6.2.1"},{"Name":"tzinfo","Version":"1.2.7"},{"Name":"tzinfo-data","Version":"1.2020.1"},{"Name":"unicode-display_width","Version":"1.7.0"},{"Name":"warden","Version":"1.2.8"},{"Name":"webdrivers","Version":"4.4.1"},{"Name":"webpacker","Version":"5.1.1"},{"Name":"websocket-driver","Version":"0.7.3"},{"Name":"websocket-extensions","Version":"0.1.5"},{"Name":"xpath","Version":"3.2.0"},{"Name":"zeitwerk","Version":"2.4.0"}]],"level":{"level":5000,"levelStr":"TRACE","colour":"blue"},"context":{},"pid":6989},
{"startTime":"2021-01-19T21:30:13.094Z","categoryName":"sonatypeIQ","data":["Getting Internal ID from Public ID: auditjs"],"level":{"level":10000,"levelStr":"DEBUG","colour":"cyan"},"context":{},"pid":6989},
{"startTime":"2021-01-19T21:30:13.095Z","categoryName":"sonatypeIQ","data":["Getting application ID from public ID: auditjs"],"level":{"level":5000,"levelStr":"TRACE","colour":"blue"},"context":{},"pid":6989},
{"startTime":"2021-01-19T21:30:13.771Z","categoryName":"sonatypeIQ","data":["Error getting application ID from public ID","https://iq.sonatype-se.com/api/v2/applications?publicId=auditjs",{}],"level":{"level":40000,"levelStr":"ERROR","colour":"red"},"context":{},"pid":6989},
{"startTime":"2021-01-19T21:30:13.772Z","categoryName":"sonatypeIQ","data":["Nexus IQ extension failure",{}],"level":{"level":40000,"levelStr":"ERROR","colour":"red"},"context":{},"pid":6989},
```

**Comment by ButterB0wl** [comment]
Better error message but still doesn't update the app until after the extension is reloaded:
image

**Review by ButterB0wl — APPROVED** [review]
Approved for the fixed error message and other testing, having to reload to apply a new app id we will do in a later PR
